#!/usr/bin/python3

import os
import sys


def print_help(exit_code):
    print("Usage:", os.path.basename(__file__), "NUMBER\n")
    print("Prints factorial of NUMBER.\n")

    exit(exit_code)


def get_factorial(num=1):
    # Input validation
    try:
        num = int(num)
    except ValueError:
        sys.stderr.write("Argument doesn't seem to be an integer.\nExiting unsuccessfully.\n")
        exit(10)

    result = num
    for i in range(1, num):
        result = result * i

    return result


def main():
    if (len(sys.argv) == 1):
        sys.stderr.write("No argument given!\n")
        print_help(1)

    if (sys.argv[1] == '-h' or sys.argv[1] == '--help'):
        print_help(0)

    print(get_factorial(sys.argv[1]))


if __name__ == "__main__":
    main()
