#!/usr/bin/python3

import os
import sys


def print_help(exit_code):
    """
    Prints help message.

    Prints help message when -h/--help parameter is used or when the program
    isn't called properly.

    Parameters
    ----------
    stream : int
        Number indicating whether help message should be printed to stdout or
        stderr.

    """

    print("Usage:", os.path.basename(__file__), "INTEGER\n")
    print("Prints factorial of INTEGER.\n")

    exit(exit_code)


def get_factorial(num=1):
    """
    Counts factorial.

    Method counts a factorial of an integer given as parameter.

    Parameters
    ----------
    num : int
        Integer for which factorial should be counted for.

    Returns
    -------
    result: int
        Value of factorial for given integer.

    """

    result = num
    for i in range(1, num):
        result = result * i

    return result


def main():
    """
    Method main().

    Start of the program.

    """

    if (len(sys.argv) == 1):
        sys.stderr.write("No argument given!\n")
        print_help(1)

    if (sys.argv[1] == '-h' or sys.argv[1] == '--help'):
        print_help(0)

    try:
        arg = int(sys.argv[1])
    except ValueError:
        sys.stderr.write(
            "Argument doesn't seem to be an integer.\nExiting unsuccessfully.\n")
        exit(10)

    print(get_factorial(arg))

    exit(0)


if __name__ == "__main__":
    main()
